[workspace]
authors = ["Nodar Gogoberidze <gnodar01@gmail.com>"]
channels = ["conda-forge"]
name = "zmk-config"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"

[pypi-dependencies]
#zmk = ">=0.2.0, <0.3"
zmk = { git = "https://github.com/gnodar01/zmk-cli.git", branch = "main" }
click = "<8.2.0"
